import Bill from "@/components/Bill";
import LayoutWithSide from "@/components/Layout/LayoutWithSide";
import Orders from "@/components/Lists/Bills";
import { useDash } from "@/hooks/useDash";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useEffect } from "react";

import AuthContent from "@/components/Auth/AuthContent";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <div className="grid grid-cols-12 ">
          <div className="col-span-3">
            <Orders />
          </div>
          <Bill />
        </div>
      </>
    </>
  );
}
